from centos

# 1) Install JDK 9
RUN wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/9.0.1+11/jdk-9.0.1_linux-x64_bin.tar.gz \ -O jdk-9.tar.gz; \
tar -xzf jdk-9.tar.gz

# 2) Copy executable jar files

# 3) Copy config files

# 4) Run client

CMD java -version